/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;
import back.Planificador;
import back.Filosofos;
import back.Palillos;
import java.awt.Color;
import java.util.Stack;
import javax.swing.ImageIcon;
import java.applet.AudioClip;
import back.ImageHandler;
import java.awt.Dimension;
/**
 *
 * @author User
 */
public class interfaz extends javax.swing.JFrame {

    
    Planificador programa = new Planificador (5);
    Filosofos []comensales;
    ImageIcon icono;
    Dimension dimension;
    ImageHandler imagen;
    AudioClip cancion;
    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        comensales = new Filosofos [5];
        cancion = java.applet.Applet.newAudioClip(getClass().getResource("/sonidos/2-14-Red-Velvet.wav"));
        imagen = new ImageHandler("/img/");
        for (int i = 0;i<5;i++){
                Filosofos temp = new Filosofos(programa,i);
                comensales[i] = temp;
        }
        dimension = new Dimension(120,100);
        filosofo0.setIcon(imagen.redimensionarImagen("miku pensando.png", dimension));
        filosofo1.setIcon(imagen.redimensionarImagen("miku pensando.png", dimension));
        filosofo2.setIcon(imagen.redimensionarImagen("miku pensando.png", dimension));
        filosofo3.setIcon(imagen.redimensionarImagen("miku pensando.png", dimension));
        filosofo4.setIcon(imagen.redimensionarImagen("miku pensando.png", dimension));
        filosofo0.setSize(dimension);
        filosofo1.setSize(dimension);
        filosofo2.setSize(dimension);
        filosofo3.setSize(dimension);
        filosofo4.setSize(dimension);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();
        filosofo0 = new javax.swing.JLabel();
        filosofo1 = new javax.swing.JLabel();
        filosofo2 = new javax.swing.JLabel();
        filosofo3 = new javax.swing.JLabel();
        filosofo4 = new javax.swing.JLabel();
        palillo0 = new javax.swing.JButton();
        palillo1 = new javax.swing.JButton();
        palillo2 = new javax.swing.JButton();
        palillo3 = new javax.swing.JButton();
        palillo4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cena de los filosofos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 22, 238, -1));

        btnEmpezar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEmpezar.setText("Empezar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 529, 110, 44));

        filosofo0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miku pensando.PNG"))); // NOI18N
        getContentPane().add(filosofo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 120, 100));

        filosofo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miku pensando.PNG"))); // NOI18N
        getContentPane().add(filosofo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 120, 100));

        filosofo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miku pensando.PNG"))); // NOI18N
        getContentPane().add(filosofo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 120, 100));

        filosofo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miku pensando.PNG"))); // NOI18N
        getContentPane().add(filosofo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 120, 100));

        filosofo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miku pensando.PNG"))); // NOI18N
        getContentPane().add(filosofo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 120, 100));

        palillo0.setBackground(new java.awt.Color(0, 153, 51));
        palillo0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        palillo0.setForeground(new java.awt.Color(0, 0, 0));
        palillo0.setText("/");
        getContentPane().add(palillo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 60, 40));

        palillo1.setBackground(new java.awt.Color(0, 153, 51));
        palillo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        palillo1.setForeground(new java.awt.Color(0, 0, 0));
        palillo1.setText("/");
        getContentPane().add(palillo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 60, 40));

        palillo2.setBackground(new java.awt.Color(0, 153, 51));
        palillo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        palillo2.setForeground(new java.awt.Color(0, 0, 0));
        palillo2.setText("/");
        getContentPane().add(palillo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 70, 40));

        palillo3.setBackground(new java.awt.Color(0, 153, 51));
        palillo3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        palillo3.setForeground(new java.awt.Color(0, 0, 0));
        palillo3.setText("/");
        getContentPane().add(palillo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 70, 40));

        palillo4.setBackground(new java.awt.Color(0, 153, 51));
        palillo4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        palillo4.setForeground(new java.awt.Color(0, 0, 0));
        palillo4.setText("/");
        getContentPane().add(palillo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 60, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        // TODO add your handling code here:
        if(!comensales[0].isAlive()){
            for (int i = 0;i<5;i++){
                comensales[i].start();
                comensales[i].iniciar();
                
            }
            cancion.loop();
            btnEmpezar.setText("Detener");
        }else if(comensales[0].isCorriendo()){
            for(int i = 0;i<5;i++){
                comensales[i].suspend();
                comensales[i].detener();
            }
            btnEmpezar.setText("Empezar");
            cancion.stop();
        }else{
            for(int i = 0;i<5;i++){
                comensales[i].resume();
                comensales[i].iniciar();
            }
            btnEmpezar.setText("Detener");
            cancion.loop();
        }
        
        actualizarUI();
        
    }//GEN-LAST:event_btnEmpezarActionPerformed

    public void actualizarUI(){
        Thread ventana = new Thread(()->{
            while(!Thread.currentThread().isInterrupted()){
                
                if(programa.getEstadoPalillo(0)){
                    palillo0.setBackground(Color.green);
                }else{
                    palillo0.setBackground(Color.red);
                }
                if(programa.getEstadoPalillo(1)){
                    palillo1.setBackground(Color.green);
                }else{
                    palillo1.setBackground(Color.red);
                }
                if(programa.getEstadoPalillo(2)){
                    palillo2.setBackground(Color.green);
                }else{
                    palillo2.setBackground(Color.red);
                }
                if(programa.getEstadoPalillo(3)){
                    palillo3.setBackground(Color.green);
                }else{
                    palillo3.setBackground(Color.red);
                }
                if(programa.getEstadoPalillo(4)){
                    palillo4.setBackground(Color.green);
                }else{
                    palillo4.setBackground(Color.red);
                }
                
                if(comensales[0].getEstado() == true){
                    filosofo0.setIcon(imagen.redimensionarImagen("miku comiendo.png", dimension));
                }else{
                    filosofo0.setIcon(imagen.redimensionarImagen("miku pensando.png", dimension));
                }
                
                if(comensales[1].getEstado() == true){
                    filosofo1.setIcon(imagen.redimensionarImagen("miku comiendo.png", dimension));
                }else{
                    filosofo1.setIcon(imagen.redimensionarImagen("miku pensando.png", dimension));
                }
                
                if(comensales[2].getEstado() == true){
                    filosofo2.setIcon(imagen.redimensionarImagen("miku comiendo.png", dimension));
                }else{
                    filosofo2.setIcon(imagen.redimensionarImagen("miku pensando.png", dimension));
                }
                
                if(comensales[3].getEstado() == true){
                    filosofo3.setIcon(imagen.redimensionarImagen("miku comiendo.png", dimension));
                }else{
                    filosofo3.setIcon(imagen.redimensionarImagen("miku pensando.png", dimension));
                }
                
                if(comensales[4].getEstado() == true){
                    filosofo4.setIcon(imagen.redimensionarImagen("miku comiendo.png", dimension));
                }else{
                    filosofo4.setIcon(imagen.redimensionarImagen("miku pensando.png", dimension));
                }
                
            }
        });
        ventana.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JLabel filosofo0;
    private javax.swing.JLabel filosofo1;
    private javax.swing.JLabel filosofo2;
    private javax.swing.JLabel filosofo3;
    private javax.swing.JLabel filosofo4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton palillo0;
    private javax.swing.JButton palillo1;
    private javax.swing.JButton palillo2;
    private javax.swing.JButton palillo3;
    private javax.swing.JButton palillo4;
    // End of variables declaration//GEN-END:variables
}
