/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;
import back.Planificador;
import back.Filosofos;
import back.Palillos;
import java.util.Stack;
import javax.swing.ImageIcon;
/**
 *
 * @author User
 */
public class interfaz extends javax.swing.JFrame {

    
    Planificador programa = new Planificador (5);
    Filosofos []comensales;
    ImageIcon icono;
    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        comensales = new Filosofos [5];
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();
        filosofo0 = new javax.swing.JLabel();
        filosofo1 = new javax.swing.JLabel();
        filosofo2 = new javax.swing.JLabel();
        filosofo3 = new javax.swing.JLabel();
        filosofo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cena de los filosofos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 22, 238, -1));

        btnEmpezar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEmpezar.setText("Empezar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 529, 110, 44));

        filosofo0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miku pensando.PNG"))); // NOI18N
        getContentPane().add(filosofo0, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 90, 80));

        filosofo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miku pensando.PNG"))); // NOI18N
        getContentPane().add(filosofo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 90, 80));

        filosofo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miku pensando.PNG"))); // NOI18N
        getContentPane().add(filosofo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 80, 80));

        filosofo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miku pensando.PNG"))); // NOI18N
        getContentPane().add(filosofo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 80, 70));

        filosofo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/miku pensando.PNG"))); // NOI18N
        getContentPane().add(filosofo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 80, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        // TODO add your handling code here:
        for (int i = 0;i<5;i++){
            Filosofos temp = new Filosofos(programa,i);
            temp.start();
            comensales[i] = temp;
        }
        actualizarUI();
    }//GEN-LAST:event_btnEmpezarActionPerformed

    public void actualizarUI(){
        Thread ventana = new Thread(()->{
            while(!Thread.currentThread().isInterrupted()){
                
                
                if(comensales[0].getEstado() == true){
                    icono = new ImageIcon(getClass().getResource("/img/miku comiendo.PNG"));   
                    filosofo0.setIcon(icono);
                }else{
                    icono = new ImageIcon(getClass().getResource("/img/miku pensando.PNG"));
                    filosofo0.setIcon(icono);
                }
                
                if(comensales[1].getEstado() == true){
                    icono = new ImageIcon(getClass().getResource("/img/miku comiendo.PNG"));   
                    filosofo1.setIcon(icono);
                }else{
                    icono = new ImageIcon(getClass().getResource("/img/miku pensando.PNG"));
                    filosofo1.setIcon(icono);
                }
                
                if(comensales[2].getEstado() == true){
                    icono = new ImageIcon(getClass().getResource("/img/miku comiendo.PNG"));   
                    filosofo2.setIcon(icono);
                }else{
                    icono = new ImageIcon(getClass().getResource("/img/miku pensando.PNG"));
                    filosofo2.setIcon(icono);
                }
                
                if(comensales[3].getEstado() == true){
                    icono = new ImageIcon(getClass().getResource("/img/miku comiendo.PNG"));   
                    filosofo3.setIcon(icono);
                }else{
                    icono = new ImageIcon(getClass().getResource("/img/miku pensando.PNG"));
                    filosofo3.setIcon(icono);
                }
                
                if(comensales[4].getEstado() == true){
                    icono = new ImageIcon(getClass().getResource("/img/miku comiendo.PNG"));   
                    filosofo4.setIcon(icono);
                }else{
                    icono = new ImageIcon(getClass().getResource("/img/miku pensando.PNG"));
                    filosofo4.setIcon(icono);
                }
                
            }
        });
        ventana.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JLabel filosofo0;
    private javax.swing.JLabel filosofo1;
    private javax.swing.JLabel filosofo2;
    private javax.swing.JLabel filosofo3;
    private javax.swing.JLabel filosofo4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
